### PR TITLE
fix: #2706

### PR DESCRIPTION
**Pull request by xiaobindebingo**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by xiaobindebingo** [comment]
> Could you please add tests to make sure this change works as expected?



> Could you please add tests to make sure this change works as expected?

ok, already run npm test

**Comment by xiaobindebingo** [comment]
> Could you please add tests to make sure this change works as expected?

**Comment by xiaobindebingo** [comment]
> Could you please add tests to make sure this change works as expected?

ok

**Comment by hustcc** [comment]
Thanks for your contribution.

**Comment by hustcc** [comment]
@xiaobindebingo 你可以帮忙尝试解决一下为什么没有指定 color 的时候会报错~

**Pull request merged**
