### PR TITLE
修复 Cannot assign to read only property 'constructor' of object '#<t>' 报错问题

### PR DESCRIPTION
**Pull request by simaQ**
### 🤔 This is a ...

与 #1339 可能有关。

- [ ] New feature
- [x] Bug fix
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] All tests pass and/or benchmarks are included
- [ ] Commit message follows commit guidelines
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

### CODE REVIEW

**Comment by afc163** [comment]
https://github.com/Microsoft/TypeScript/issues/6887
http://zhanglun.xyz/2017/01/19/%E6%95%B4%E7%90%86Object%E7%9A%84%E4%B8%80%E4%BA%9B%E6%96%B9%E6%B3%95/

留作参考

**Comment by afc163** [comment]
https://juejin.im/post/5d8a11c1518825096f3b0aed

**Comment by qozi** [comment]
我使用 [vue-cli-plugin-electron-builder](https://github.com/nklayman/vue-cli-plugin-electron-builder) 打包, 通过 viser-vue 使用 g2 也出现类似异常。

异常信息：
```
Uncaught TypeError: Cannot assign to read only property 'constructor' of object '#<t>'
    at n (g2-plugin-slider.js:502)
    at g2-plugin-slider.js:518
    at Object.<anonymous> (g2-plugin-slider.js:517)
    at n (g2-plugin-slider.js:30)
    at Object.<anonymous> (g2-plugin-slider.js:96)
    at n (g2-plugin-slider.js:30)
    at Object.<anonymous> (g2-plugin-slider.js:80)
    at n (g2-plugin-slider.js:30)
    at g2-plugin-slider.js:73
    at g2-plugin-slider.js:11
```
详细描述见 [issue](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1089#issuecomment-1165802847)

我报错是 [g2-plugin-slider](https://github.com/antvis/g2-plugin-slider) 这个库，是不是 g2 的相关模块都可能存在这个问题。

**Comment by JaneYork** [comment]
> issue

后来怎么处理的？引用外部CDN？

**Pull request merged**
