### PR TITLE
add size-plugin

### PR DESCRIPTION
**Pull request by kuldeepkeshwar**
### 🤔 This is a tooling update. added `size-plugin`

- [ ] New feature
- [ ] Bug fix
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [x] Other (tooling)

### CODE REVIEW

**Comment by hustcc** [comment]
Thanks for you contribution, but the pr will write `size-plugin.json` every commit, this will lead to a lot of meaningless commit diff.

So we are sorry for that we can't accept your pr. Glad to wait for your further contribution.

**Comment by kuldeepkeshwar** [comment]
@hustcc it doesn't write to `size-plugin.json` on every commit.

**Comment by hustcc** [comment]
when the bundle size changed, will update the size？

**Comment by kuldeepkeshwar** [comment]
only when there is any change in the default branch(in our case it is `master`).

It is already working  in https://github.com/antvis/component

**Pull request closed without merging**
