### PR TITLE
docs: add area graph demos (#5897)

### PR DESCRIPTION
**Pull request by foolvip**
> close: https://github.com/antvis/G2/issues/5897

### CODE REVIEW

**Comment by pearmini** [comment]
可以把每个 demo 的截图发给我，我上传之后把链接给你，然后你更新到 meta.json 里面。

**Comment by foolvip** [comment]
image
image
image
image
image

现在meta.json 文件里已经添加了缩略图，是4.0版本的 @pearmini

**Comment by pearmini** [comment]
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*HjBUTp_hSlgAAAAAAAAAAAAADmJ7AQ/original
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*HjBUTp_hSlgAAAAAAAAAAAAADmJ7AQ/original
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*FiZJRI8pHL4AAAAAAAAAAAAADmJ7AQ/original
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*FiZJRI8pHL4AAAAAAAAAAAAADmJ7AQ/original
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*_x_WSo465k0AAAAAAAAAAAAADmJ7AQ/original

**Comment by hustcc** [comment]
> * https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*HjBUTp_hSlgAAAAAAAAAAAAADmJ7AQ/original
> * https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*HjBUTp_hSlgAAAAAAAAAAAAADmJ7AQ/original
> * https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*FiZJRI8pHL4AAAAAAAAAAAAADmJ7AQ/original
> * https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*FiZJRI8pHL4AAAAAAAAAAAAADmJ7AQ/original
> * https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*_x_WSo465k0AAAAAAAAAAAAADmJ7AQ/original

@pearmini  截图应该不需要标题吧？其他的案例都没有。

**Comment by pearmini** [comment]
> @pearmini 截图应该不需要标题吧？其他的案例都没有。

@hustcc @foolvip 确实哈，这个地方可以把标题去掉。

**Comment by hustcc** [comment]
你在现有截图基础上，重新截图一次即可。

**Comment by foolvip** [comment]
> 你在现有截图基础上，重新截图一次即可。

image
image
image
image
image

**Comment by pearmini** [comment]
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*oDcJTangPsgAAAAAAAAAAAAADmJ7AQ/original
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*HlorR55MDE4AAAAAAAAAAAAADmJ7AQ/original
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*VDBoSreSzqUAAAAAAAAAAAAADmJ7AQ/original
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*VDBoSreSzqUAAAAAAAAAAAAADmJ7AQ/original
- https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*9cV1Rq1rr8EAAAAAAAAAAAAADmJ7AQ/original

@foolvip 新的链接

**Comment by foolvip** [comment]
> * https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*oDcJTangPsgAAAAAAAAAAAAADmJ7AQ/original
> * https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*HlorR55MDE4AAAAAAAAAAAAADmJ7AQ/original
> * https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*VDBoSreSzqUAAAAAAAAAAAAADmJ7AQ/original
> * https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*VDBoSreSzqUAAAAAAAAAAAAADmJ7AQ/original
> * https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*9cV1Rq1rr8EAAAAAAAAAAAAADmJ7AQ/original
> 
> @foolvip 新的链接

第三个和第四个链接的图片是一样的，缺少了简单面积图 @pearmini

**Comment by pearmini** [comment]
@foolvip 抱歉，已经更新了：

https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*v1VOS7lUmckAAAAAAAAAAAAADmJ7AQ/original

**Comment by foolvip** [comment]
> 更新



> @foolvip 抱歉，已经更新了：
> 
> https://mdn.alipayobjects.com/huamei_qa8qxu/afts/img/A*v1VOS7lUmckAAAAAAAAAAAAADmJ7AQ/original

已经更新提交了

**Review by pearmini — APPROVED** [review]
🚀🚀🚀

**Comment by pearmini** [comment]
感谢给 G2 贡献代码，欢迎加入 G2 开源先锋群！

**Pull request merged**
