### PR TITLE
fix: modify the coordinate property call method.

### PR DESCRIPTION
**Pull request by simaQ**
### 🤔 This is a ...

- [ ] New feature
- [ ] Bug fix
- [ ] Component style update
- [ ] TypeScript definition update
- [x] Refactoring
- [x] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### ☑️ Self Check before Merge

- [ ] All tests pass and/or benchmarks are included
- [ ] Commit message follows commit guidelines
- [ ] TypeScript definition is updated/provided or not needed
- [ ] Changelog is provided or not needed

Related https://github.com/antvis/coord/pull/5

### CODE REVIEW

**Comment by hustcc** [comment]
单测挂了，之前是 3 个，现在有 5 个了~

**Comment by simaQ** [comment]
> 单测挂了，之前是 3 个，现在有 5 个了~

搞不懂为啥子会挂啊

**Comment by hustcc** [comment]
> > 单测挂了，之前是 3 个，现在有 5 个了~
> 
> 搞不懂为啥子会挂啊

和这个 mr 没有关系，先合并了。

**Comment by simaQ** [comment]
> > > 单测挂了，之前是 3 个，现在有 5 个了~
> > 
> > 
> > 搞不懂为啥子会挂啊
> 
> 和这个 mr 没有关系，先合并了。

恩，看来这么写 case 不太合适，不同的运行时环境会有不一样的结果... 很坑啊

**Pull request merged**
